// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpiJG2KmVZ8FVLqQOBsSQd3djLxyTv9yk',
    appId: '1:508474665669:web:2203fca05ae59b2c08deac',
    messagingSenderId: '508474665669',
    projectId: 'chatify-8a345',
    authDomain: 'chatify-8a345.firebaseapp.com',
    storageBucket: 'chatify-8a345.appspot.com',
    measurementId: 'G-JZFZ5LF8M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhrRltU2JeEsZBM8m5-gFMbnJiQCSS0Us',
    appId: '1:508474665669:android:3796aa00a6a5c2aa08deac',
    messagingSenderId: '508474665669',
    projectId: 'chatify-8a345',
    storageBucket: 'chatify-8a345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDmxlyrCioLcVSQ-28ux1zFOAe17bh2WE',
    appId: '1:508474665669:ios:531d08109904726008deac',
    messagingSenderId: '508474665669',
    projectId: 'chatify-8a345',
    storageBucket: 'chatify-8a345.appspot.com',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDmxlyrCioLcVSQ-28ux1zFOAe17bh2WE',
    appId: '1:508474665669:ios:531d08109904726008deac',
    messagingSenderId: '508474665669',
    projectId: 'chatify-8a345',
    storageBucket: 'chatify-8a345.appspot.com',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpiJG2KmVZ8FVLqQOBsSQd3djLxyTv9yk',
    appId: '1:508474665669:web:1ab25273047b147908deac',
    messagingSenderId: '508474665669',
    projectId: 'chatify-8a345',
    authDomain: 'chatify-8a345.firebaseapp.com',
    storageBucket: 'chatify-8a345.appspot.com',
    measurementId: 'G-X2YM0PD6PX',
  );
}
